# Generated by Django 5.0 on 2024-02-17 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
