# Generated by Django 5.0 on 2024-02-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='uid',
            field=models.IntegerField(editable=False, unique=True),
        ),
    ]
