# Generated by Django 5.0 on 2024-07-04 11:55

import django.utils.timezone
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='j_created',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
