# Generated by Django 5.0 on 2024-02-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='uid',
            field=models.IntegerField(default=100, editable=False, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productgallery',
            name='uid',
            field=models.IntegerField(default=100, editable=False, unique=True),
            preserve_default=False,
        ),
    ]
