# Generated by Django 5.0 on 2024-03-13 13:20

import core.core.file_presave
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_uid_productgallery_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='cover_image',
        ),
        migrations.AddField(
            model_name='product',
            name='hover_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.core.file_presave.upload_image_path),
        ),
    ]
