# Generated by Django 5.0 on 2024-07-05 06:33

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_image_product_cover_image_product_hover_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='productgallery',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
