# Generated by Django 5.0 on 2024-07-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_bought_count_product_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='score',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
    ]
