# Generated by Django 5.0 on 2024-07-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bought',
            field=models.IntegerField(default=0),
        ),
    ]
