# Generated by Django 5.0 on 2024-07-06 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_bought'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bought',
        ),
    ]
