# Generated by Django 5.0 on 2024-07-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_product_bought'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('NO', 'None'), ('MN', 'Man'), ('WN', 'Woman')], default='NO', max_length=2),
        ),
    ]
