# Generated by Django 5.0 on 2024-07-17 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='group',
        ),
    ]
