# Generated by Django 5.0 on 2024-07-17 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_product_group'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='branch',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tags.branch'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(related_name='tags', related_query_name='tags', to='tags.tags'),
        ),
    ]
