# Generated by Django 5.0 on 2024-07-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bought_count',
            field=models.IntegerField(default=0),
        ),
    ]
