# Generated by Django 5.0 on 2024-07-18 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_product_bought_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bought_count',
        ),
    ]
