# Generated by Django 5.0 on 2023-12-20 16:52

import core.core.file_presave
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterTableHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='you can set some items to this head in rows section', max_length=70)),
                ('active', models.BooleanField(blank=True, default=True, help_text='When you set this option to False, this column will no longer be displayed on the website')),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['-id'], name='sitesetting_id_693e34_idx')],
            },
            managers=[
                ('address_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='this only visible in admin-panel', max_length=80)),
                ('name', models.CharField(help_text='this will be applied to the site', max_length=50)),
                ('image', models.ImageField(help_text='this is a small picture of your social-media', upload_to=core.core.file_presave.upload_image_path)),
                ('link', models.URLField(help_text='please enter your social-media page link here')),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['-id'], name='sitesetting_id_e19635_idx')],
            },
            managers=[
                ('address_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='FooterTableRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='this is for display in rows of table head', max_length=70)),
                ('link', models.URLField(blank=True, help_text='enter the url of some site section for on_click option')),
                ('table_head', models.ForeignKey(help_text='assign item to a table head', on_delete=django.db.models.deletion.CASCADE, to='sitesetting.footertablehead')),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['-id'], name='sitesetting_id_840b34_idx')],
            },
            managers=[
                ('address_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='this is only for display setting config in admin panel', max_length=100)),
                ('brand_name', models.CharField(help_text='enter your site title here', max_length=100)),
                ('company_address', models.CharField(blank=True, help_text='write your company address here', max_length=300, null=True)),
                ('phone', models.BigIntegerField(blank=True, help_text='enter your company phone number', null=True)),
                ('fax', models.BigIntegerField(blank=True, help_text='enter your company fax', null=True)),
                ('email_address', models.EmailField(blank=True, help_text='enter your site support email address here', max_length=254, null=True)),
                ('logo', models.ImageField(upload_to=core.core.file_presave.upload_image_path)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('copy_right', models.CharField(blank=True, help_text='write copyright text here', max_length=300, null=True)),
                ('about_us', models.TextField(help_text='enter some information about your business')),
                ('active', models.BooleanField(default=False, help_text='this checkbox means these settings should be replaced to your current site settingsif you make this True, the currently active settings will be automatically disabledand these settings will be applied to the site')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('social_media', models.ManyToManyField(help_text='if you do not have social-media yet...please add one from social-media section', to='sitesetting.socialmedia')),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['-id'], name='sitesetting_id_1481dc_idx')],
            },
            managers=[
                ('address_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
