# Generated by Django 5.0 on 2024-07-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grouptags',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tags',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
