# Generated by Django 5.0 on 2024-07-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_branch_active_grouptags_active_tags_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='grouptags',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
