# Generated by Django 5.0 on 2024-07-17 15:24

import core.core.file_presave
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_alter_branch_managers_alter_grouptags_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.core.file_presave.upload_image_path),
        ),
    ]
