# Generated by Django 5.0 on 2024-04-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0002_favorite_session_uid_alter_favorite_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='session_uid',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
