# Generated by Django 5.0 on 2024-04-06 16:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0003_alter_favorite_session_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='session_uid',
            field=models.CharField(default=uuid.uuid4, max_length=100),
        ),
    ]
