# Generated by Django 5.0 on 2024-04-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0004_alter_favorite_session_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='session_uid',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
