# Generated by Django 5.0 on 2024-07-05 06:33

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0005_alter_favorite_session_uid'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='favorite',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
