# Generated by Django 5.0 on 2024-04-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='session_id',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
