# Generated by Django 5.0 on 2024-04-06 16:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_order_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='session_id',
            field=models.CharField(default=uuid.uuid4, max_length=100),
        ),
    ]
