# Generated by Django 5.0 on 2024-04-26 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_order_session_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='session_id',
            new_name='session_uid',
        ),
    ]
