# Generated by Django 5.0 on 2024-04-29 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_rename_session_id_order_session_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='session_uid',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
