# Generated by Django 5.0 on 2024-06-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_alter_order_session_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='offer_code',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('OP', 'OPEN'), ('PE', 'PENDING'), ('IP', 'IN_PROGRESS'), ('CM', 'COMPLETED'), ('CA', 'CANCELLED'), ('ER', 'ERROR')], default='OP', max_length=2),
        ),
        migrations.AddField(
            model_name='order',
            name='step',
            field=models.CharField(choices=[('OP', 'OPEN'), ('DI', 'DELIVERY_INFO'), ('WP', 'WAITING_FOR_PAYMENT'), ('PD', 'PAID'), ('CA', 'CANCELLED'), ('ER', 'ERROR')], default='OP', max_length=2),
        ),
    ]
