# Generated by Django 5.0 on 2024-07-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_order_offer_code_order_status_order_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='step',
            field=models.CharField(choices=[('OP', 'OPEN'), ('AD', 'ADDRESSING'), ('CO', 'CHECKOUT'), ('RC', 'RECEIPT'), ('PA', 'PAYMENT'), ('CA', 'CANCELLED'), ('ER', 'ERROR')], default='OP', max_length=2),
        ),
    ]
