# Generated by Django 5.0 on 2024-07-04 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_address_j_created'),
        ('cart', '0009_alter_order_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.address'),
        ),
        migrations.AddField(
            model_name='order',
            name='address_confirmed',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
