# Generated by Django 5.0 on 2024-07-04 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_order_address_order_address_confirmed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address_confirmed',
            new_name='address_finalized',
        ),
    ]
