# Generated by Django 5.0 on 2024-07-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_alter_order_managers_alter_orderitem_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='step_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
