# Generated by Django 5.0 on 2024-07-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_order_step_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='step_updated',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
    ]
