# Generated by Django 5.0 on 2024-07-05 07:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_alter_order_step_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='step_updated',
            field=models.DateTimeField(auto_created=True, blank=True, default=datetime.datetime(2024, 7, 5, 7, 16, 19, 966038, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
